/* This file was generated by CMake/glv_parametrization_parser.*/
#pragma once

glvm_parametrization(ConfigType2,"ConfigType2", 
	contour, double, "-c", "contour description", 0.0040000000000000001)

glvm_parametrization(ConfigType,"ConfigType", 
	bound, double, "-b", "bound description", 0.002,
	kernel, bool, "-k", "kernel description", true,
	ConfigType2_var, ConfigType2, "Subadvanced", "Subadvanced description", ConfigType2())

glvm_parametrization(Parametrization,"Parametrization", 
	bar, int, "-bar", "bar description", 4,
	file, SlvFile, "-file", "file description", "/path/path/",
	foo, float, "-foo", "foo description", 77.769999999999996f,
	ConfigType_var, ConfigType, "Advanced", "Advanced description", ConfigType())

